name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Retrieve opam cache
        uses: actions/cache@v4
        with:
          path: _opam
          key: ${{ runner.os }}-${{ hashFiles('certified_base.opam.locked') }}

      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "4.14"
          dune-cache: true

      - run: opam install . --deps-only --with-test --locked
        shell: bash

      - name: Build (dune build)
        run: opam exec -- dune build
        shell: bash

      - name: Test (dune test)
        run: opam exec -- dune test
        shell: bash
